# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from client_python import remote_file_pb2 as remote__file__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in remote_file_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RemoteFileSystemStub(object):
    """Serviço: sistema de arquivos remoto básico
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Abre = channel.unary_unary(
                '/remotefs.RemoteFileSystem/Abre',
                request_serializer=remote__file__pb2.OpenRequest.SerializeToString,
                response_deserializer=remote__file__pb2.OpenResponse.FromString,
                _registered_method=True)
        self.Le = channel.unary_unary(
                '/remotefs.RemoteFileSystem/Le',
                request_serializer=remote__file__pb2.ReadRequest.SerializeToString,
                response_deserializer=remote__file__pb2.ReadResponse.FromString,
                _registered_method=True)
        self.Escreve = channel.unary_unary(
                '/remotefs.RemoteFileSystem/Escreve',
                request_serializer=remote__file__pb2.WriteRequest.SerializeToString,
                response_deserializer=remote__file__pb2.WriteResponse.FromString,
                _registered_method=True)
        self.Fecha = channel.unary_unary(
                '/remotefs.RemoteFileSystem/Fecha',
                request_serializer=remote__file__pb2.CloseRequest.SerializeToString,
                response_deserializer=remote__file__pb2.CloseResponse.FromString,
                _registered_method=True)
        self.Ls = channel.unary_unary(
                '/remotefs.RemoteFileSystem/Ls',
                request_serializer=remote__file__pb2.LsRequest.SerializeToString,
                response_deserializer=remote__file__pb2.LsResponse.FromString,
                _registered_method=True)


class RemoteFileSystemServicer(object):
    """Serviço: sistema de arquivos remoto básico
    """

    def Abre(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Le(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Escreve(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Fecha(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Ls(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RemoteFileSystemServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Abre': grpc.unary_unary_rpc_method_handler(
                    servicer.Abre,
                    request_deserializer=remote__file__pb2.OpenRequest.FromString,
                    response_serializer=remote__file__pb2.OpenResponse.SerializeToString,
            ),
            'Le': grpc.unary_unary_rpc_method_handler(
                    servicer.Le,
                    request_deserializer=remote__file__pb2.ReadRequest.FromString,
                    response_serializer=remote__file__pb2.ReadResponse.SerializeToString,
            ),
            'Escreve': grpc.unary_unary_rpc_method_handler(
                    servicer.Escreve,
                    request_deserializer=remote__file__pb2.WriteRequest.FromString,
                    response_serializer=remote__file__pb2.WriteResponse.SerializeToString,
            ),
            'Fecha': grpc.unary_unary_rpc_method_handler(
                    servicer.Fecha,
                    request_deserializer=remote__file__pb2.CloseRequest.FromString,
                    response_serializer=remote__file__pb2.CloseResponse.SerializeToString,
            ),
            'Ls': grpc.unary_unary_rpc_method_handler(
                    servicer.Ls,
                    request_deserializer=remote__file__pb2.LsRequest.FromString,
                    response_serializer=remote__file__pb2.LsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'remotefs.RemoteFileSystem', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('remotefs.RemoteFileSystem', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RemoteFileSystem(object):
    """Serviço: sistema de arquivos remoto básico
    """

    @staticmethod
    def Abre(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/remotefs.RemoteFileSystem/Abre',
            remote__file__pb2.OpenRequest.SerializeToString,
            remote__file__pb2.OpenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Le(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/remotefs.RemoteFileSystem/Le',
            remote__file__pb2.ReadRequest.SerializeToString,
            remote__file__pb2.ReadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Escreve(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/remotefs.RemoteFileSystem/Escreve',
            remote__file__pb2.WriteRequest.SerializeToString,
            remote__file__pb2.WriteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Fecha(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/remotefs.RemoteFileSystem/Fecha',
            remote__file__pb2.CloseRequest.SerializeToString,
            remote__file__pb2.CloseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Ls(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/remotefs.RemoteFileSystem/Ls',
            remote__file__pb2.LsRequest.SerializeToString,
            remote__file__pb2.LsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
